//AVCONECC.h
#ifndef __AVCONECC_H__
#define __AVCONECC_H__


#include <VIDEC/VIDEC_CodecDef.h>
#include <AUDEC/AUDEC_CodecID.h>

#define HP_AUDIO_CODEC_TYPE		X_AUDIO_CODEC_ID

#define X_AUDIO_CODEC_AVAC_8	X_AUDIO_CODEC_AMR_WB_9
#define X_AUDIO_CODEC_AVAC_16	X_AUDIO_CODEC_AMR_WB_16
#define X_AUDIO_CODEC_AVAC_24	X_AUDIO_CODEC_G7221_14_24
#define X_AUDIO_CODEC_AVAC_32	X_AUDIO_CODEC_G7221_14_32
#define X_AUDIO_CODEC_AVAC_48	X_AUDIO_CODEC_G7221_14_48
	


#endif